services:
  app_pg_connector:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.pg_connector
    environment:
      CONNECTION_URI: $APP_PG_CONNECTOR_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_PG_CONNECTOR_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_PG_CONNECTOR_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_PG_CONNECTOR_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 9738:8080
